version: '3'
services:
  
  backend:
    build: ./backend
    container_name: PCBackend
    ports:
      - 5000:5000
    environment:
      -MONGO_URI=mongodb://admin:mongo@mongodb:27017
      -REDIS_URI=redis://admin:redis@redis:6379

  frontend:
    build: ./frontend
    container_name: PCFrontend
    ports:
      - 80:80
    environment:
      - REACT_APP_BACKEND_URL="http://backend:5000"
  
  redis:
    image: redis
    container_name: redis
    environment:
      - REDIS_USERNAME=admin
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017